[package]
name = "grid_search"
description = "Collection of searching algorithms"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/grid-search.git"
repository = "https://github.com/stevebob/grid-search.git"
documentation = "https://docs.rs/grid_search"

[dependencies]
direction = "0.6"
grid_2d = "0.1"
num-traits = "0.1"
